### ISSUE TITLE
Unhandled stream error crashes app

### ISSUE THREAD

**Issue by zachsa** [SAEON/data-portal#4]
This error crops up in the logs quite often:

```
2021-06-23T10:51:28.204+00:00
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  status: 500
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @catalogue/api@2.0.3 start:prod: `TZ=utc node --no-warnings --experimental-json-modules src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @catalogue/api@2.0.3 start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-23T10_51_28_229Z-debug.log
```

Must have a fix!

**Comment by zachsa** [comment]
Haven't heard anything more about this. Have you @clairedavis-reddy? If not I'm going to close this issue

**Comment by clairedavis-reddy** [comment]
No, I have not. You can close this issue.
